OPTI = -Ofast
WAR = -g3 -Wall
THREAD = -lpthread

all: exo1 exo2 exo3

exo1:
	gcc -o reduction reduc.c ${THREAD} ${WAR} ${OPTI}
	
exo2:
	gcc -o $@.exe $@.c ${THREAD} ${WAR} ${OPTI}
	
exo3:
	gcc -o $@.exe $@.c ${THREAD} ${WAR} ${OPTI}
