OPTI = -Ofast

all: exo1 exo2 exo3

exo1:
	gcc -o reduction reduc.c -lpthread -g3 -Wall ${OPTI}
	
exo2:
	gcc -o exo2.exe exo2.c -lpthread -g3 -Wall ${OPTI}
	
exo3:
	gcc -o exo3.exe exo3.c -lpthread -g3 -Wall ${OPTI}
