WD = -g3 -Wall

GCC = gcc -o

EXO = exo

compil:
	${GCC} ${EXO}1 ${EXO}1.c ${WD}
	${GCC} ${EXO}2 ${EXO}2.c ${WD}
	${GCC} ${EXO}3 ${EXO}3.c ${WD}
	${GCC} ${EXO}4 ${EXO}4.c ${WD}
	${GCC} ${EXO}5 ${EXO}5.c ${WD}
	
run1:
	./${EXO}1
	
run2:
	./${EXO}2
	
run3:
	./${EXO}3
	
run4:
	./${EXO}4

run5:
	./${EXO}5
	
